services:
  postgres:
    image: postgres:17-alpine
    shm_size: 1gb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${DEGOV_DB_PASSWORD:-postgres}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${DEGOV_DB_PORT:-5432}:5432"

  web:
    image: degov-web
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "${DEGOV_WEB_PORT:-3000}:3000"
    environment:
      JWT_SECRET_KEY: ${DEGOV_WEB_JWT_SECRET}
      DATABASE_URL: postgresql://postgres:${DEGOV_DB_PASSWORD:-postgres}@postgres/degov
      # DEGOV_CONFIG_PATH: degov.yml
