module.exports = class Data1774864102235 {
    name = 'Data1774864102235'

    async up(db) {
        await db.query(`CREATE TABLE "delegate_changed" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "delegator" text NOT NULL, "from_delegate" text NOT NULL, "to_delegate" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_82fcd22b1159cec837a6062982f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0fed007c6b7b9a0d5db284a1ad" ON "delegate_changed" ("chain_id", "governor_address", "delegator") `)
        await db.query(`CREATE TABLE "delegate_votes_changed" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "delegate" text NOT NULL, "previous_votes" numeric NOT NULL, "new_votes" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_a38fef07a3e775591ad1d4de0ad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8b36c6f37c8e64f25dd9e5264d" ON "delegate_votes_changed" ("chain_id", "governor_address", "delegate") `)
        await db.query(`CREATE TABLE "token_transfer" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "from" text NOT NULL, "to" text NOT NULL, "value" numeric NOT NULL, "standard" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_77384b7f5874553f012eba9da41" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_121840740598d8260873c7de04" ON "token_transfer" ("transaction_hash") `)
        await db.query(`CREATE INDEX "IDX_e3fe323128cc8da72b2d7b5d6a" ON "token_transfer" ("chain_id", "governor_address", "token_address") `)
        await db.query(`CREATE TABLE "vote_power_checkpoint" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "account" text NOT NULL, "clock_mode" text NOT NULL, "timepoint" numeric NOT NULL, "previous_power" numeric NOT NULL, "new_power" numeric NOT NULL, "delta" numeric NOT NULL, "cause" text NOT NULL, "delegator" text, "from_delegate" text, "to_delegate" text, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_a7046c290a7a7d881283853f3f7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_08c8f53fdccf02212a8da0ee1e" ON "vote_power_checkpoint" ("chain_id", "governor_address", "token_address", "account", "clock_mode", "timepoint") `)
        await db.query(`CREATE TABLE "proposal_canceled" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_22622253f3a27d143c7fea33d7c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ce8974da5dced94a5a3fb7849f" ON "proposal_canceled" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_created" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "proposer" text NOT NULL, "targets" text array NOT NULL, "values" text array NOT NULL, "signatures" text array NOT NULL, "calldatas" text array NOT NULL, "vote_start" numeric NOT NULL, "vote_end" numeric NOT NULL, "description" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_a7f756da7b761d1eda0c80d7de3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0baf06a475c01030f465b563e6" ON "proposal_created" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_executed" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_0b159cbdd0cf4c05709dc7b8955" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_236183a9fbc8bab05c572325b0" ON "proposal_executed" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_queued" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "eta_seconds" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_49df9d6b2bd83692cde2dc4fbb1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_58acbeb4d04c455acbc8b18617" ON "proposal_queued" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_extended" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "extended_deadline" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_6045f56e0b59c31883e6c922518" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6497bb4d1d1da3179a4776f4e7" ON "proposal_extended" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "voting_delay_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_voting_delay" numeric NOT NULL, "new_voting_delay" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_8983d8dda9ac173d838f0ee816f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1d0559b433db64cb1e046de623" ON "voting_delay_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "voting_period_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_voting_period" numeric NOT NULL, "new_voting_period" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c1af519d2daa15edb846387251d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_97bcfcbb15905bb0a91f92d683" ON "voting_period_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "proposal_threshold_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_proposal_threshold" numeric NOT NULL, "new_proposal_threshold" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_0cfd9709a913d0120b57bf053e1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_91a300b1dee04cacc8e7b6f7a8" ON "proposal_threshold_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "quorum_numerator_updated" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_quorum_numerator" numeric NOT NULL, "new_quorum_numerator" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_da8046638ae69bb6e6792cfcaf8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7976d16bd699ca225a24f662e8" ON "quorum_numerator_updated" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "late_quorum_vote_extension_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_late_quorum_vote_extension" numeric NOT NULL, "new_late_quorum_vote_extension" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_41c7ff87ec4deb20d4512b03c4b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_575153f59f35050a99a0ab62f9" ON "late_quorum_vote_extension_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "timelock_change" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_timelock" text NOT NULL, "new_timelock" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_029a7fd2e1fb70da29695ecc658" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1aab88f67a4f19b479684940ec" ON "timelock_change" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "vote_cast" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "voter" text NOT NULL, "proposal_id" text NOT NULL, "support" integer NOT NULL, "weight" numeric NOT NULL, "reason" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_4ac5f0845939b5be9a3528c868e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_51a29cfd1e5f71932317a66133" ON "vote_cast" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "vote_cast_with_params" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "voter" text NOT NULL, "proposal_id" text NOT NULL, "support" integer NOT NULL, "weight" numeric NOT NULL, "reason" text NOT NULL, "params" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_9569ed7f1b6e52cd9ff923e47e7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_74f9e8ec92107a0e3e0e9011e8" ON "vote_cast_with_params" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_action" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "action_index" integer NOT NULL, "target" text NOT NULL, "value" text NOT NULL, "signature" text NOT NULL, "calldata" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c44bd6250cf241ddd15782e8b55" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ac8a482f4b80a3f4254739d334" ON "proposal_action" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_0081b098486e1dff1a5a520154" ON "proposal_action" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_state_epoch" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "state" text NOT NULL, "start_timepoint" numeric, "end_timepoint" numeric, "start_block_number" numeric, "start_block_timestamp" numeric, "end_block_number" numeric, "end_block_timestamp" numeric, "transaction_hash" text NOT NULL, CONSTRAINT "PK_86628fadab571d1088cfdc3b0b9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f964649484ed88d3d8a9551fbf" ON "proposal_state_epoch" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_5900ad3243dbf121ad225f980e" ON "proposal_state_epoch" ("chain_id", "governor_address", "proposal_id", "state") `)
        await db.query(`CREATE TABLE "proposal_deadline_extension" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "previous_deadline" numeric, "new_deadline" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_51f84b19ac7d6e3972e711ece46" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_772d21a997bce2920ef6b8edf9" ON "proposal_deadline_extension" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_394553e0ed1896ef6d97e0a1b0" ON "proposal_deadline_extension" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "timelock_call" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "timelock_address" text NOT NULL, "contract_address" text, "log_index" integer, "transaction_index" integer, "operation_id" character varying NOT NULL, "proposal_id" character varying, "proposal_action_id" text, "proposal_action_index" integer, "action_index" integer NOT NULL, "target" text NOT NULL, "value" text NOT NULL, "data" text NOT NULL, "predecessor" text, "delay_seconds" numeric, "state" text NOT NULL, "scheduled_block_number" numeric, "scheduled_block_timestamp" numeric, "scheduled_transaction_hash" text, "executed_block_number" numeric, "executed_block_timestamp" numeric, "executed_transaction_hash" text, CONSTRAINT "PK_dae843ead23b71257e61fae484e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5a89e85fcddd1c5120a66ddff3" ON "timelock_call" ("operation_id") `)
        await db.query(`CREATE INDEX "IDX_02e9680cc4905d667deaec230b" ON "timelock_call" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_d2c4c75619b38113cc07d29be2" ON "timelock_call" ("chain_id", "governor_address", "timelock_address", "operation_id", "action_index") `)
        await db.query(`CREATE TABLE "timelock_operation" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "timelock_address" text NOT NULL, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying, "operation_id" text NOT NULL, "timelock_type" text NOT NULL, "predecessor" text, "salt" text, "state" text NOT NULL, "call_count" integer, "executed_call_count" integer, "delay_seconds" numeric, "ready_at" numeric, "expires_at" numeric, "queued_block_number" numeric, "queued_block_timestamp" numeric, "queued_transaction_hash" text, "cancelled_block_number" numeric, "cancelled_block_timestamp" numeric, "cancelled_transaction_hash" text, "executed_block_number" numeric, "executed_block_timestamp" numeric, "executed_transaction_hash" text, CONSTRAINT "PK_80f1a4c38f9180ca2af3328a2b8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4f85eaf0fa034e10124101ad01" ON "timelock_operation" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_1d57ae87a833af26036523041b" ON "timelock_operation" ("chain_id", "governor_address", "timelock_address", "proposal_id", "operation_id") `)
        await db.query(`CREATE TABLE "proposal" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "proposer" text NOT NULL, "targets" text array NOT NULL, "values" text array NOT NULL, "signatures" text array NOT NULL, "calldatas" text array NOT NULL, "vote_start" numeric NOT NULL, "vote_end" numeric NOT NULL, "description" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "metrics_votes_count" integer, "metrics_votes_with_params_count" integer, "metrics_votes_without_params_count" integer, "metrics_votes_weight_for_sum" numeric, "metrics_votes_weight_against_sum" numeric, "metrics_votes_weight_abstain_sum" numeric, "title" text NOT NULL, "vote_start_timestamp" numeric NOT NULL, "vote_end_timestamp" numeric NOT NULL, "block_interval" text, "description_hash" text, "proposal_snapshot" numeric, "proposal_deadline" numeric, "proposal_eta" numeric, "queue_ready_at" numeric, "queue_expires_at" numeric, "counting_mode" text, "timelock_address" text, "timelock_grace_period" numeric, "clock_mode" text NOT NULL, "quorum" numeric NOT NULL, "decimals" numeric NOT NULL, CONSTRAINT "PK_ca872ecfe4fef5720d2d39e4275" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c2956b263206187757df55ad45" ON "proposal" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "vote_cast_group" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "type" text NOT NULL, "voter" text NOT NULL, "ref_proposal_id" text NOT NULL, "support" integer NOT NULL, "weight" numeric NOT NULL, "reason" text NOT NULL, "params" text, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "proposal_id" character varying, CONSTRAINT "PK_b64558b70e64cb753bf9007352c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_46ec520941027c99068c7ed24b" ON "vote_cast_group" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_35b8709ea26d346c86d9ee76e3" ON "vote_cast_group" ("chain_id", "governor_address", "ref_proposal_id") `)
        await db.query(`CREATE TABLE "governance_parameter_checkpoint" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "event_name" text NOT NULL, "parameter_name" text NOT NULL, "value_type" text NOT NULL, "old_value" text, "new_value" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c69f0d3c9b2b7f3125abca6297a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_64d60087312e6ae04581a81da5" ON "governance_parameter_checkpoint" ("chain_id", "governor_address", "parameter_name") `)
        await db.query(`CREATE TABLE "timelock_role_event" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "timelock_address" text NOT NULL, "contract_address" text, "log_index" integer, "transaction_index" integer, "event_name" text NOT NULL, "role" text NOT NULL, "role_label" text, "account" text, "sender" text, "previous_admin_role" text, "previous_admin_role_label" text, "new_admin_role" text, "new_admin_role_label" text, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_9ca37fd5648a81b8799cd7307d4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5ff9c27463cdecb92a4b7ccff9" ON "timelock_role_event" ("chain_id", "governor_address", "timelock_address", "role", "event_name") `)
        await db.query(`CREATE TABLE "timelock_min_delay_change" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "timelock_address" text NOT NULL, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_duration" numeric NOT NULL, "new_duration" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_116a972c9389a86114c0f676c84" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b98caad15a83928f8b5fa657b2" ON "timelock_min_delay_change" ("chain_id", "governor_address", "timelock_address", "block_number") `)
        await db.query(`CREATE TABLE "data_metric" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposals_count" integer, "votes_count" integer, "votes_with_params_count" integer, "votes_without_params_count" integer, "votes_weight_for_sum" numeric, "votes_weight_against_sum" numeric, "votes_weight_abstain_sum" numeric, "power_sum" numeric, "member_count" integer, CONSTRAINT "PK_25f5e39e9c7755e2233bcbdc255" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_95c80384fafd3caf17631ee3a4" ON "data_metric" ("chain_id", "governor_address", "dao_code") `)
        await db.query(`CREATE TABLE "delegate_rolling" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "delegator" text NOT NULL, "from_delegate" text NOT NULL, "to_delegate" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "from_previous_votes" numeric, "from_new_votes" numeric, "to_previous_votes" numeric, "to_new_votes" numeric, CONSTRAINT "PK_976ac6dd5a215cf1276bbf56adf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_40c2d2d26c1139b07284a7ed7e" ON "delegate_rolling" ("transaction_hash") `)
        await db.query(`CREATE INDEX "IDX_f68da56408b641c4ed4d4e1a96" ON "delegate_rolling" ("chain_id", "governor_address", "delegator") `)
        await db.query(`CREATE TABLE "delegate" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "from_delegate" text NOT NULL, "to_delegate" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "is_current" boolean NOT NULL, "power" numeric NOT NULL, CONSTRAINT "PK_810516365b3daa9f6d6d2d4f2b7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3ff4b3a851b38f29afb15bafcc" ON "delegate" ("chain_id", "governor_address", "from_delegate", "to_delegate") `)
        await db.query(`CREATE TABLE "contributor" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "last_vote_block_number" numeric, "last_vote_timestamp" numeric, "power" numeric NOT NULL, "delegates_count_all" integer NOT NULL, "delegates_count_effective" integer NOT NULL, CONSTRAINT "PK_816afef005b8100becacdeb6e58" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_34d8a39d812fd6841f0cd49238" ON "contributor" ("chain_id", "governor_address", "id") `)
        await db.query(`CREATE TABLE "delegate_mapping" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "token_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "from" text NOT NULL, "to" text NOT NULL, "power" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_5b8f4a7ecb81f46845fa636443c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b593bc2d019039d306e64c5128" ON "delegate_mapping" ("chain_id", "governor_address", "from") `)
        await db.query(`ALTER TABLE "proposal_action" ADD CONSTRAINT "FK_ac8a482f4b80a3f4254739d334b" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proposal_state_epoch" ADD CONSTRAINT "FK_f964649484ed88d3d8a9551fbf3" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proposal_deadline_extension" ADD CONSTRAINT "FK_772d21a997bce2920ef6b8edf9d" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "timelock_call" ADD CONSTRAINT "FK_5a89e85fcddd1c5120a66ddff3e" FOREIGN KEY ("operation_id") REFERENCES "timelock_operation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "timelock_call" ADD CONSTRAINT "FK_02e9680cc4905d667deaec230b5" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "timelock_operation" ADD CONSTRAINT "FK_4f85eaf0fa034e10124101ad013" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vote_cast_group" ADD CONSTRAINT "FK_46ec520941027c99068c7ed24b8" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "delegate_changed"`)
        await db.query(`DROP INDEX "public"."IDX_0fed007c6b7b9a0d5db284a1ad"`)
        await db.query(`DROP TABLE "delegate_votes_changed"`)
        await db.query(`DROP INDEX "public"."IDX_8b36c6f37c8e64f25dd9e5264d"`)
        await db.query(`DROP TABLE "token_transfer"`)
        await db.query(`DROP INDEX "public"."IDX_121840740598d8260873c7de04"`)
        await db.query(`DROP INDEX "public"."IDX_e3fe323128cc8da72b2d7b5d6a"`)
        await db.query(`DROP TABLE "vote_power_checkpoint"`)
        await db.query(`DROP INDEX "public"."IDX_08c8f53fdccf02212a8da0ee1e"`)
        await db.query(`DROP TABLE "proposal_canceled"`)
        await db.query(`DROP INDEX "public"."IDX_ce8974da5dced94a5a3fb7849f"`)
        await db.query(`DROP TABLE "proposal_created"`)
        await db.query(`DROP INDEX "public"."IDX_0baf06a475c01030f465b563e6"`)
        await db.query(`DROP TABLE "proposal_executed"`)
        await db.query(`DROP INDEX "public"."IDX_236183a9fbc8bab05c572325b0"`)
        await db.query(`DROP TABLE "proposal_queued"`)
        await db.query(`DROP INDEX "public"."IDX_58acbeb4d04c455acbc8b18617"`)
        await db.query(`DROP TABLE "proposal_extended"`)
        await db.query(`DROP INDEX "public"."IDX_6497bb4d1d1da3179a4776f4e7"`)
        await db.query(`DROP TABLE "voting_delay_set"`)
        await db.query(`DROP INDEX "public"."IDX_1d0559b433db64cb1e046de623"`)
        await db.query(`DROP TABLE "voting_period_set"`)
        await db.query(`DROP INDEX "public"."IDX_97bcfcbb15905bb0a91f92d683"`)
        await db.query(`DROP TABLE "proposal_threshold_set"`)
        await db.query(`DROP INDEX "public"."IDX_91a300b1dee04cacc8e7b6f7a8"`)
        await db.query(`DROP TABLE "quorum_numerator_updated"`)
        await db.query(`DROP INDEX "public"."IDX_7976d16bd699ca225a24f662e8"`)
        await db.query(`DROP TABLE "late_quorum_vote_extension_set"`)
        await db.query(`DROP INDEX "public"."IDX_575153f59f35050a99a0ab62f9"`)
        await db.query(`DROP TABLE "timelock_change"`)
        await db.query(`DROP INDEX "public"."IDX_1aab88f67a4f19b479684940ec"`)
        await db.query(`DROP TABLE "vote_cast"`)
        await db.query(`DROP INDEX "public"."IDX_51a29cfd1e5f71932317a66133"`)
        await db.query(`DROP TABLE "vote_cast_with_params"`)
        await db.query(`DROP INDEX "public"."IDX_74f9e8ec92107a0e3e0e9011e8"`)
        await db.query(`DROP TABLE "proposal_action"`)
        await db.query(`DROP INDEX "public"."IDX_ac8a482f4b80a3f4254739d334"`)
        await db.query(`DROP INDEX "public"."IDX_0081b098486e1dff1a5a520154"`)
        await db.query(`DROP TABLE "proposal_state_epoch"`)
        await db.query(`DROP INDEX "public"."IDX_f964649484ed88d3d8a9551fbf"`)
        await db.query(`DROP INDEX "public"."IDX_5900ad3243dbf121ad225f980e"`)
        await db.query(`DROP TABLE "proposal_deadline_extension"`)
        await db.query(`DROP INDEX "public"."IDX_772d21a997bce2920ef6b8edf9"`)
        await db.query(`DROP INDEX "public"."IDX_394553e0ed1896ef6d97e0a1b0"`)
        await db.query(`DROP TABLE "timelock_call"`)
        await db.query(`DROP INDEX "public"."IDX_5a89e85fcddd1c5120a66ddff3"`)
        await db.query(`DROP INDEX "public"."IDX_02e9680cc4905d667deaec230b"`)
        await db.query(`DROP INDEX "public"."IDX_d2c4c75619b38113cc07d29be2"`)
        await db.query(`DROP TABLE "timelock_operation"`)
        await db.query(`DROP INDEX "public"."IDX_4f85eaf0fa034e10124101ad01"`)
        await db.query(`DROP INDEX "public"."IDX_1d57ae87a833af26036523041b"`)
        await db.query(`DROP TABLE "proposal"`)
        await db.query(`DROP INDEX "public"."IDX_c2956b263206187757df55ad45"`)
        await db.query(`DROP TABLE "vote_cast_group"`)
        await db.query(`DROP INDEX "public"."IDX_46ec520941027c99068c7ed24b"`)
        await db.query(`DROP INDEX "public"."IDX_35b8709ea26d346c86d9ee76e3"`)
        await db.query(`DROP TABLE "governance_parameter_checkpoint"`)
        await db.query(`DROP INDEX "public"."IDX_64d60087312e6ae04581a81da5"`)
        await db.query(`DROP TABLE "timelock_role_event"`)
        await db.query(`DROP INDEX "public"."IDX_5ff9c27463cdecb92a4b7ccff9"`)
        await db.query(`DROP TABLE "timelock_min_delay_change"`)
        await db.query(`DROP INDEX "public"."IDX_b98caad15a83928f8b5fa657b2"`)
        await db.query(`DROP TABLE "data_metric"`)
        await db.query(`DROP INDEX "public"."IDX_95c80384fafd3caf17631ee3a4"`)
        await db.query(`DROP TABLE "delegate_rolling"`)
        await db.query(`DROP INDEX "public"."IDX_40c2d2d26c1139b07284a7ed7e"`)
        await db.query(`DROP INDEX "public"."IDX_f68da56408b641c4ed4d4e1a96"`)
        await db.query(`DROP TABLE "delegate"`)
        await db.query(`DROP INDEX "public"."IDX_3ff4b3a851b38f29afb15bafcc"`)
        await db.query(`DROP TABLE "contributor"`)
        await db.query(`DROP INDEX "public"."IDX_34d8a39d812fd6841f0cd49238"`)
        await db.query(`DROP TABLE "delegate_mapping"`)
        await db.query(`DROP INDEX "public"."IDX_b593bc2d019039d306e64c5128"`)
        await db.query(`ALTER TABLE "proposal_action" DROP CONSTRAINT "FK_ac8a482f4b80a3f4254739d334b"`)
        await db.query(`ALTER TABLE "proposal_state_epoch" DROP CONSTRAINT "FK_f964649484ed88d3d8a9551fbf3"`)
        await db.query(`ALTER TABLE "proposal_deadline_extension" DROP CONSTRAINT "FK_772d21a997bce2920ef6b8edf9d"`)
        await db.query(`ALTER TABLE "timelock_call" DROP CONSTRAINT "FK_5a89e85fcddd1c5120a66ddff3e"`)
        await db.query(`ALTER TABLE "timelock_call" DROP CONSTRAINT "FK_02e9680cc4905d667deaec230b5"`)
        await db.query(`ALTER TABLE "timelock_operation" DROP CONSTRAINT "FK_4f85eaf0fa034e10124101ad013"`)
        await db.query(`ALTER TABLE "vote_cast_group" DROP CONSTRAINT "FK_46ec520941027c99068c7ed24b8"`)
    }
}
