module.exports = class Data1774405762738 {
    name = 'Data1774405762738'

    async up(db) {
        await db.query(`CREATE TABLE "proposal_extended" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" text NOT NULL, "extended_deadline" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_6045f56e0b59c31883e6c922518" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6497bb4d1d1da3179a4776f4e7" ON "proposal_extended" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "voting_delay_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_voting_delay" numeric NOT NULL, "new_voting_delay" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_8983d8dda9ac173d838f0ee816f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1d0559b433db64cb1e046de623" ON "voting_delay_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "voting_period_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_voting_period" numeric NOT NULL, "new_voting_period" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c1af519d2daa15edb846387251d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_97bcfcbb15905bb0a91f92d683" ON "voting_period_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "proposal_threshold_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_proposal_threshold" numeric NOT NULL, "new_proposal_threshold" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_0cfd9709a913d0120b57bf053e1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_91a300b1dee04cacc8e7b6f7a8" ON "proposal_threshold_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "quorum_numerator_updated" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_quorum_numerator" numeric NOT NULL, "new_quorum_numerator" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_da8046638ae69bb6e6792cfcaf8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7976d16bd699ca225a24f662e8" ON "quorum_numerator_updated" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "late_quorum_vote_extension_set" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_late_quorum_vote_extension" numeric NOT NULL, "new_late_quorum_vote_extension" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_41c7ff87ec4deb20d4512b03c4b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_575153f59f35050a99a0ab62f9" ON "late_quorum_vote_extension_set" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "timelock_change" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "old_timelock" text NOT NULL, "new_timelock" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_029a7fd2e1fb70da29695ecc658" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1aab88f67a4f19b479684940ec" ON "timelock_change" ("chain_id", "governor_address", "block_number") `)
        await db.query(`CREATE TABLE "proposal_action" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "action_index" integer NOT NULL, "target" text NOT NULL, "value" text NOT NULL, "signature" text NOT NULL, "calldata" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c44bd6250cf241ddd15782e8b55" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ac8a482f4b80a3f4254739d334" ON "proposal_action" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_0081b098486e1dff1a5a520154" ON "proposal_action" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "proposal_state_epoch" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "state" text NOT NULL, "start_timepoint" numeric, "end_timepoint" numeric, "start_block_number" numeric, "start_block_timestamp" numeric, "end_block_number" numeric, "end_block_timestamp" numeric, "transaction_hash" text NOT NULL, CONSTRAINT "PK_86628fadab571d1088cfdc3b0b9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f964649484ed88d3d8a9551fbf" ON "proposal_state_epoch" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_5900ad3243dbf121ad225f980e" ON "proposal_state_epoch" ("chain_id", "governor_address", "proposal_id", "state") `)
        await db.query(`CREATE TABLE "proposal_deadline_extension" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "proposal_id" character varying NOT NULL, "previous_deadline" numeric, "new_deadline" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_51f84b19ac7d6e3972e711ece46" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_772d21a997bce2920ef6b8edf9" ON "proposal_deadline_extension" ("proposal_id") `)
        await db.query(`CREATE INDEX "IDX_394553e0ed1896ef6d97e0a1b0" ON "proposal_deadline_extension" ("chain_id", "governor_address", "proposal_id") `)
        await db.query(`CREATE TABLE "governance_parameter_checkpoint" ("id" character varying NOT NULL, "chain_id" integer, "dao_code" text, "governor_address" text, "contract_address" text, "log_index" integer, "transaction_index" integer, "event_name" text NOT NULL, "parameter_name" text NOT NULL, "value_type" text NOT NULL, "old_value" text, "new_value" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_c69f0d3c9b2b7f3125abca6297a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_64d60087312e6ae04581a81da5" ON "governance_parameter_checkpoint" ("chain_id", "governor_address", "parameter_name") `)
        await db.query(`ALTER TABLE "proposal" ADD "description_hash" text`)
        await db.query(`ALTER TABLE "proposal" ADD "proposal_snapshot" numeric`)
        await db.query(`ALTER TABLE "proposal" ADD "proposal_deadline" numeric`)
        await db.query(`ALTER TABLE "proposal" ADD "proposal_eta" numeric`)
        await db.query(`ALTER TABLE "proposal" ADD "counting_mode" text`)
        await db.query(`ALTER TABLE "proposal" ADD "timelock_address" text`)
        await db.query(`ALTER TABLE "proposal_action" ADD CONSTRAINT "FK_ac8a482f4b80a3f4254739d334b" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proposal_state_epoch" ADD CONSTRAINT "FK_f964649484ed88d3d8a9551fbf3" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proposal_deadline_extension" ADD CONSTRAINT "FK_772d21a997bce2920ef6b8edf9d" FOREIGN KEY ("proposal_id") REFERENCES "proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "proposal_extended"`)
        await db.query(`DROP INDEX "public"."IDX_6497bb4d1d1da3179a4776f4e7"`)
        await db.query(`DROP TABLE "voting_delay_set"`)
        await db.query(`DROP INDEX "public"."IDX_1d0559b433db64cb1e046de623"`)
        await db.query(`DROP TABLE "voting_period_set"`)
        await db.query(`DROP INDEX "public"."IDX_97bcfcbb15905bb0a91f92d683"`)
        await db.query(`DROP TABLE "proposal_threshold_set"`)
        await db.query(`DROP INDEX "public"."IDX_91a300b1dee04cacc8e7b6f7a8"`)
        await db.query(`DROP TABLE "quorum_numerator_updated"`)
        await db.query(`DROP INDEX "public"."IDX_7976d16bd699ca225a24f662e8"`)
        await db.query(`DROP TABLE "late_quorum_vote_extension_set"`)
        await db.query(`DROP INDEX "public"."IDX_575153f59f35050a99a0ab62f9"`)
        await db.query(`DROP TABLE "timelock_change"`)
        await db.query(`DROP INDEX "public"."IDX_1aab88f67a4f19b479684940ec"`)
        await db.query(`DROP TABLE "proposal_action"`)
        await db.query(`DROP INDEX "public"."IDX_ac8a482f4b80a3f4254739d334"`)
        await db.query(`DROP INDEX "public"."IDX_0081b098486e1dff1a5a520154"`)
        await db.query(`DROP TABLE "proposal_state_epoch"`)
        await db.query(`DROP INDEX "public"."IDX_f964649484ed88d3d8a9551fbf"`)
        await db.query(`DROP INDEX "public"."IDX_5900ad3243dbf121ad225f980e"`)
        await db.query(`DROP TABLE "proposal_deadline_extension"`)
        await db.query(`DROP INDEX "public"."IDX_772d21a997bce2920ef6b8edf9"`)
        await db.query(`DROP INDEX "public"."IDX_394553e0ed1896ef6d97e0a1b0"`)
        await db.query(`DROP TABLE "governance_parameter_checkpoint"`)
        await db.query(`DROP INDEX "public"."IDX_64d60087312e6ae04581a81da5"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "description_hash"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "proposal_snapshot"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "proposal_deadline"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "proposal_eta"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "counting_mode"`)
        await db.query(`ALTER TABLE "proposal" DROP COLUMN "timelock_address"`)
        await db.query(`ALTER TABLE "proposal_action" DROP CONSTRAINT "FK_ac8a482f4b80a3f4254739d334b"`)
        await db.query(`ALTER TABLE "proposal_state_epoch" DROP CONSTRAINT "FK_f964649484ed88d3d8a9551fbf3"`)
        await db.query(`ALTER TABLE "proposal_deadline_extension" DROP CONSTRAINT "FK_772d21a997bce2920ef6b8edf9d"`)
    }
}
