name: DeGov Development Test DAO
logo: "/example/logo.svg"
# The deployedChain value must be one of the chains in the network config
deployedChain: darwinia
description:
  DeGov is a open-sourced governance platform that allows users to create
  and participate in decentralized governance.
# The following fields in the links are optional and will be used to display basic information about the DAO
links:
  website: https://ringdao.com/
  twitter: https://x.com/ringecosystem
  discord: https://discord.com/invite/BhNbKWWfGV
  telegram: https://t.me/ringecosystem
  github: https://github.com/ringecosystem/degov
  email:  # It's ok to leave it empty
walletConnectProjectId: 2719448e2ce94fdd269a3c8587123bcc
networks:
  darwinia:
    logo: https://darwinia.network/images/darwinia-logo-black-background-round.svg
    chainId: 46
    rpc:
      - https://rpc.darwinia.network
      - https://darwinia-rpc.dwellir.com
    explorer:
      - https://explorer.darwinia.network/
    nativeToken:
      symbol: RING
      decimals: 18
      priceId: RING
contracts:
  governor: "0x9bCF89B951b9880AC1Ec9Ce6b82B2764ca7A532F"
  governorToken:
    contract: 
    standard: ERC20 
  timeLock: "0x527560d6a509ddE7828D598BF31Fc67DA50c8093"
indexer:
  endpoint: https://degov-indexer.vercel.app/graphql
timeLockAssets:
  mtk:
    chain: darwinia
    contract: "0x9d633f05Ea918D392bDa0A74bD15E5bcCad324e2"
    standard: ERC20
    priceId: MTK
    logo: 
  usdt:
    chain: darwinia
    contract: "0x8D71a40566fa4dCEE390Bbf854f63D43d06a90fd"
    standard: ERC721
    priceId: MTK
    logo: 
