export enum ChainId {
  ETHEREUM = 1,
  ARBITRUM = 42161,
  DARWINIA = 46,
  ETHEREUM_SEPOLIA = 11155111,
  ARBITRUM_SEPOLIA = 421614,
}

export const SUPPORT_CHAINS = [
  ChainId.ETHEREUM,
  ChainId.ARBITRUM,
  ChainId.DARWINIA,
  ChainId.ETHEREUM_SEPOLIA,
  ChainId.ARBITRUM_SEPOLIA,
];
