#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DataMetricWrite {
    pub id: String,
    pub contract_set_id: String,
    pub chain_id: i32,
    pub dao_code: String,
    pub governor_address: String,
    pub token_address: Option<String>,
    pub contract_address: Option<String>,
    pub log_index: Option<u64>,
    pub transaction_index: Option<u64>,
    pub block_number: String,
    pub proposals_count: Option<i64>,
    pub votes_count: Option<i64>,
    pub votes_with_params_count: Option<i64>,
    pub votes_without_params_count: Option<i64>,
    pub votes_weight_for_sum: Option<String>,
    pub votes_weight_against_sum: Option<String>,
    pub votes_weight_abstain_sum: Option<String>,
    pub power_sum: Option<String>,
    pub member_count: Option<i64>,
}
